README.md: guessinggame.sh
	echo "guessing game project" > README.md
	echo "" >> README.md
	echo "date and time of run" >> README.md
	date >> README.md
	echo "" >> README.md
	echo "number of lines in guessinggame.sh" >> README.md
	wc -l < guessinggame.sh >> README.md